# Generated by Django 4.2.4 on 2023-08-20 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orphanageRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=250, verbose_name='Orphanage Role Name')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orphanageRolesCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orphanageRolesUpdatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Orphanage Roles',
                'db_table': 'orphanage_roles',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=250, verbose_name='Profile Name')),
                ('dob', models.DateTimeField()),
                ('profile_photo1', models.ImageField(blank=True, null=True, upload_to='profile_photo/', verbose_name='Profile Photo 1')),
                ('profile_photo2', models.ImageField(blank=True, null=True, upload_to='profile_photo/', verbose_name='Profile Photo 2')),
                ('profile_photo3', models.ImageField(blank=True, null=True, upload_to='profile_photo/', verbose_name='Profile Photo 3')),
                ('encoded_photo1', models.BinaryField(blank=True, null=True, verbose_name='Profile Photo 1 Encoded')),
                ('encoded_photo2', models.BinaryField(blank=True, null=True, verbose_name='Profile Photo 2 Encoded')),
                ('encoded_photo3', models.BinaryField(blank=True, null=True, verbose_name='Profile Photo 3 Encoded')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProfileCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.orphanageroles', verbose_name='Orphanage Roles Id')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProfileUpdatedBy', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Id')),
            ],
            options={
                'verbose_name_plural': 'Profile',
                'db_table': 'profile',
            },
        ),
    ]
