# Generated by Django 4.2.4 on 2023-08-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orphanageroles',
            options={'verbose_name_plural': 'Orphanage Roles'},
        ),
        migrations.AlterModelTable(
            name='orphanageroles',
            table='orphanage_roles',
        ),
    ]
