# Generated by Django 4.2.4 on 2023-08-08 13:12

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orphan_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo1', models.ImageField(max_length=300, upload_to=webapp.models.Rename.save)),
                ('photo2', models.ImageField(blank=True, max_length=300, upload_to=webapp.models.Rename.save)),
                ('photo3', models.ImageField(blank=True, max_length=300, upload_to=webapp.models.Rename.save)),
                ('encoding1', models.BinaryField(blank=True, null=True)),
                ('encoding2', models.BinaryField(blank=True, null=True)),
                ('encoding3', models.BinaryField(blank=True, null=True)),
                ('photoUI', models.ImageField(blank=True, editable=False, max_length=300, upload_to='')),
            ],
        ),
    ]
